### ISSUE TITLE
Preapare the mid-project review presentation

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#66]
# ToDos:

1. Create a presentation with slides about the software that will include 
- [x] a short description of what our project is about.
- [x] User personas and user stories
- [x] Description of a good use case 
- [x] Demo time: consideration for the time it will take within the 

2. Plan the demo of the project.
- [x] create a demo scenario and document the steps that are needed to demostrate the execution of the scenario from a user perspective
- [x] repeat the steps enough times until they are clear and can be performed without stressing out.

#### Official description from the deliverables document

> **Mid-project review**
> Every product owner be ready to demo your software. If you get to demo, please: 
> - State shortly what your project is about
> - Demo one good use case
> - Use personas and stories, not user1 or test_data
> - Finish within 10 min. max.
